# Generated by Django 4.0 on 2021-12-26 21:27

from datetime import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('valor', models.FloatField()),
                ('data_cadastro', models.DateTimeField(default=datetime(2021, 12, 26, 18, 27, 57, 61003))),
            ],
        ),
    ]
