# Generated by Django 4.0 on 2022-01-17 04:17

from django.utils.datetime_safe import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carromodel',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.now()),
        ),
    ]
